# Change these first
owner: ccns # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Alpine Linux Mirror
    url: https://alpine.ccns.ncku.edu.tw/alpine
  - name: CentOS Linux Mirror
    url: https://centos.ccns.ncku.edu.tw/centos
  - name: Debian Linux Mirror
    url: https://debian.ccns.ncku.edu.tw/debian
  - name: Discord Invitation
    url: https://discord.ccns.io
  - name: Grafana
    url: $GRAFANA_URL
  - name: CCNS IPAM
    url: $CCNS_IPAM_URL
  - name: CCNS Kubernetes
    url: $CCNS_K8S_URL
  - name: CCNS LibreNMS
    url: $CCNS_LIBRENMS_URL
  - name: CCNS Minecraft Map
    url: https://mc-map.ccns.io
  - name: CCNS CodiMD
    url: $CCNS_CODIMD_URL
  - name: CCNS NAS
    url: https://nas.ccns.io
  - name: CCNS Passbolt
    url: $CCNS_PASSBOLT_URL
  - name: CCNS Proxmox VE
    url: https://pve.ccns.io
  - name: CCNS Registry
    url: https://registry.ccns.io
  - name: CCNS Smokeping Landing Page
    url: https://smokeping.ccns.io
  - name: CCNS Smokeping TANet TNN-1
    url: https://smokeping-tanet-tnn-1.ccns.io
  - name: Ubuntu Linux Mirror
    url: https://ubuntu.ccns.ncku.edu.tw/ubuntu
  - name: CCNS UniFi Controller
    url: $CCNS_UNIFI_URL

assignees:
  - TsundereChen
status-website:
  theme: dark
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.ccns.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://i.imgur.com/DxIXOiu.png
  name: CCNS Uptime
  introTitle: "CCNS Uptime monitoring services"
  introMessage: CCNS service uptime monitor.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/ccns/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
